# Generated by Django 4.1.3 on 2022-12-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("icon", models.ImageField(upload_to="")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DeployedEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=20, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.SlugField(max_length=20, unique=True)),
            ],
            options={
                "ordering": ("tag",),
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="apps_library.application",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="apps_library.deployedenvironment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="deployments",
            field=models.ManyToManyField(
                related_name="applications",
                through="apps_library.Deployment",
                to="apps_library.deployedenvironment",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="applications", to="apps_library.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="deployment",
            constraint=models.UniqueConstraint(
                fields=("application", "environment"),
                name="apps_library_deployment_unique_application_by_environment",
            ),
        ),
    ]
